package com.sky.pro.HW10_libraries;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;


// Generated by https://start.springboot.io
// 优质的 spring/boot/data/security/cloud 框架中文文档尽在 => https://springdoc.cn

@SpringBootApplication
public class Hw10LibrariesApplication {

	public static void main(String[] args) {
		SpringApplication.run(Hw10LibrariesApplication.class, args);
	}

}
